### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by goubethegurt** [ghostcodekc/openExcelItemsInChrome#1]
Just want to say the program works like a charm. The only issue I've run into so far is when the program is pulling data from the description field into a new browser tab, the program will stop at a special character and move to the next line.

EX:
The line would read "Pairs of gloves, mens & womens, knit, assorted"

The program would pull "Pairs of gloves, mens" and move to the next line essentially omitting the special character and anything after it.

**Comment by ghostcodekc** [comment]
This has been resolved. 
You should pull the new code from the repository. Thank you for submitting this!
